import com.autodesk.wpe.dsl.build.BuildInfo
import com.autodesk.wpe.dsl.build.ServicesBuildHelper

@Library(['PSL@master', 'jenkins-shared-lib', 'jenkins-modules', 'wpe-shared-library@psl_2.0']) _

def common_sonar
def buildInfo = new BuildInfo(currentBuild: currentBuild, moduleName: "testinghub-autobot", stack: "test")
def serviceBuildHelper = new ServicesBuildHelper(this, 'svc_d_artifactory', buildInfo)

pipeline {

    agent {
        label 'aws-centos'
    }

    triggers {
        cron 'H 2 * * *'
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        timestamps()
    }

    parameters {
        booleanParam(name: 'CJT', defaultValue: false, description: 'Run CJT Regression ?')
        booleanParam(name: 'LIFT', defaultValue: false, description: 'Run LIFT Regression ?')
        booleanParam(name: 'APOLLO', defaultValue: false, description: 'Run Apollo Regression ?')

    }

    stages {
        stage('Prepare environment') {
            when {
                not {
                    anyOf {
                        triggeredBy 'TimerTrigger'
                        expression {
                            params.CJT == true ||
                                    params.LIFT == true ||
                                    params.APOLLO == true
                        }
                    }
                }
            }
            steps {
                script {
                    common_sonar = new ors.utils.CommonSonar(steps, env, docker)

                    // pull source
                    checkout scm
                }
            }
        }

        stage('Build Maven Project') {
            when {
                not {
                    anyOf {
                        triggeredBy 'TimerTrigger'
                        expression {
                            params.CJT == true ||
                                    params.LIFT == true ||
                                    params.APOLLO == true
                        }
                    }
                }
            }
            agent {
                docker {
                    image 'artifactory.dev.adskengineer.net/autodeskcloud/ctr-ci-slave-jdk-11:latest'
                    args '-v /mnt/data/.m2:/home/jenkins/.m2'
                    reuseNode true
                }
            }
            steps {
                script {
                    sh "mvn clean install -DskipTests"
                }
            }
        }

        stage('SonarQube code quality scan') {
            when {
                not {
                    anyOf {
                        triggeredBy 'TimerTrigger'
                        expression {
                            params.CJT == true ||
                                    params.LIFT == true ||
                                    params.APOLLO == true
                        }
                    }
                }
            }
            agent {
                docker {
                    image 'artifactory.dev.adskengineer.net/autodeskcloud/ctr-ci-slave-jdk-11:latest'
                    args '-v /mnt/data/.m2:/home/jenkins/.m2'
                    reuseNode true
                }
            }
            steps {
                script {
                    common_sonar.do_maven_scan(trunk: "${env.BRANCH_NAME}")
                }
            }
        }

        stage('Regression') {
            when {
                branch 'master'
                anyOf {
                    triggeredBy 'TimerTrigger'
                    expression {
                        params.CJT == true
                    }
                }
            }
            steps {
                echo 'Initiating Customer Lifecycle Tests'

                script {
                    println("Building Testing Hub API Input Map - estore")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/estore/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"CLT - GUAC Orders","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"BiC Native Order US","testcasename":"validateBicNativeOrder","description":"BiC Native Order - US ","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order UK","testcasename":"validateBicNativeOrder","description":"BiC Native Order - UK ","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"BACS","store":"STORE-UK","sku":"default:1","email":"","locale":"en_GB"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order DE  SEPA","testcasename":"validateBicNativeOrder","description":"BiC Native Order - DE - SEPA","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"SEPA","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order DE  GIROPAY","testcasename":"validateBicNativeOrder","description":"BiC Native Order - DE - GIROPAY","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"GIROPAY","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order AUS  ZIP","testcasename":"validateBicNativeOrder","description":"BiC Native Order - AUS - ZIP","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"ZIP","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_AU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Add seats from GUAC","testcasename":"validateBicAddSeats","description":"Add seats from GUAC","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-guac-addseats","testMethod":"validateBicAddSeats","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC order Flex","testcasename":"validateBicFlexOrder","description":"BiC order Flex","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-flexorder","testMethod":"validateBicFlexOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"META order","testcasename":"validateBicMetaOrder","description":"META order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-metaorder","testMethod":"validateBicMetaOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"MOE order","testcasename":"validateBicNativeOrderMoe","description":"MOE order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.MOEOrderFlows","testGroup":"bic-nativeorder-moe","testMethod":"validateBicNativeOrderMoe","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC refund order PAYPAL","testcasename":"validateBicRefundOrder","description":"BiC refund order - PAYPAL","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICRefundOrder","testGroup":"bic-RefundOrder","testMethod":"validateBicRefundOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"PAYPAL","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC refund order VISA","testcasename":"validateBicRefundOrder","description":"BiC refund order - VISA","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICRefundOrder","testGroup":"bic-RefundOrder","testMethod":"validateBicRefundOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC order with existing user","testcasename":"validateBicReturningUser","description":"BiC order with existing user","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-returningUser","testMethod":"validateBicReturningUser","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC renew order","testcasename":"validateRenewBicOrder","description":"BiC renew recurring order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC PromoCode order","testcasename":"promocodeBicOrder","description":"BiC Order with PromoCoder","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderPromoCode","testGroup":"bic-promocode-order","testMethod":"promocodeBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Trial Download","testcasename":"validateTrialDownloadUI","description":"BiC Trial Download","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"trialDownload-UI","testMethod":"validateTrialDownloadUI","parameters":{"application":"ece"},"testdata":{"usertype":"new","payment":"MASTERCARD","store":"STORE-NAMER","sku":"default:1","email":"guac-ct-cc-us-20210820@ssttest.net","password":"test1234"},"notsupportedenv":[],"wiki":""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - estore")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - estore')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - estore')
                    }
                }
                script {
                    println("Building Testing Hub API Input Map - accountportal")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/accountportal/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"CLT - Account Portal Order","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"Add Seats","testcasename":"validateBicAddSeatNativeOrder","description":"Add Seats from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-addseat-native","testMethod":"validateBicAddSeatNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"MASTERCARD","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Reduce Seats","testcasename":"validateBicReduceSeats","description":"Reduce Seats from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-reduceseats-native","testMethod":"validateBicReduceSeats","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"MASTERCARD","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Change Payment","testcasename":"validateBICChangePaymentProfile","description":"Change Payment from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-changePayment","testMethod":"validateBICChangePaymentProfile","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Switch Term","testcasename":"validateBicNativeOrderSwitchTerm","description":"Switch Term for BiC Order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder-switch-term","testMethod":"validateBicNativeOrderSwitchTerm","parameters":{"application":"ece","payment":"VISA","store":"STORE-NAMER"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Restart Subscription","testcasename":"validateRestartSubscription","description":"Restart a Canceled Subscription","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-restart-subscription","testMethod":"validateRestartSubscription","parameters":{"application":"ece","payment":"VISA","store":"STORE-NAMER"},"testdata":{},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Align Billing","testcasename":"validateAlignBilling","description":"Align 2 Subscriptions to same Renewal from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-align-billing","testMethod":"validateAlignBilling","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname": "Indirect Order in Portal", "testcasename": "validateBICIndirectSAPOrder", "description": "SAP Order in Portal", "os": "windows", "testClass": "com.autodesk.ece.bic.testsuites.IndirectOrderCreation", "testGroup": "sap-bicindirect", "testMethod": "validateBICIndirectSAPOrder", "parameters": { "application": "ece" }, "testdata": { "sku": "057M1-WWN886-L563:1", "salesorg": "3000", "SAPConfigLocation": "C:\\\\TestingHub\\\\SAPConfig" }, "notsupportedenv": [], "wiki": ""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - accountportal")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - accountportal')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - accountportal')
                    }
                }
                script {
                    println("Building Testing Hub API Input Map - EDU ")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/edu/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"EDU Deploy Tests","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"Educator flow","testcasename":"validateProductActivationByEducator","description":"Activate Educator Product","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.EDUUserFlows","testGroup":"activate-product-educator","testMethod":"validateProductActivationByEducator","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Student Flow","testcasename":"validateNewStudentSubscription","description":"Student Subscription flow","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.EDUUserFlows","testGroup":"validate-student-subscription","testMethod":"validateNewStudentSubscription","parameters":{"application":"ece"},"testdata":{"usertype":"new","payment":"ACH","password":"","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Design Competition Mentor Flow","testcasename":"validateMentorUser","description":"Design competition mentor flow","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.EDUUserFlows","testGroup":"validate-mentor-user","testMethod":"validateMentorUser","parameters":{"application":"ece","store":"STORE-NAMER"},"testdata":{"usertype":"existing","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":"https://wiki.autodesk.com/pages/viewpage.action?spaceKey=EFDE&title=Automation+Command+Line"}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - EDU Tests")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - EDU Tests')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - EDU Tests')
                    }
                }
            }
        }

        stage('LiftForward Financing Regression') {
            when {
                branch 'master'
                expression {
                    params.LIFT == true
                }
            }
            steps {
                echo 'Initiating LiftForward Financing UAT Regression'

                script {
                    println("Building Testing Hub API Input Map - estore")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/estore/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"LiftForward Financing Regression - GUAC Orders","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"BiC Native Order Financing","testcasename":"validateBicNativeOrder","description":"BiC Native Order - US ","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Financing Declined Order","testcasename":"validateBicNativeFinancingDeclinedOrder","description":"BiC Financing Order Declined","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICFinancingOrder","testGroup":"bic-financing-declined","testMethod":"validateBicNativeFinancingDeclinedOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Financing Canceled Order","testcasename":"validateBicNativeFinancingCanceledOrder","description":"BiC Financing Order Canceled","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICFinancingOrder","testGroup":"bic-financing-canceled","testMethod":"validateBicNativeFinancingCanceledOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC PromoCode order","testcasename":"promocodeBicOrder","description":"BiC Order with PromoCoder","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderPromoCode","testGroup":"bic-promocode-order","testMethod":"promocodeBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"META order Financing","testcasename":"validateBicMetaOrder","description":"META order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-metaorder","testMethod":"validateBicMetaOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC refund order Financing","testcasename":"validateBicRefundOrder","description":"BiC refund order - LIFT","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICRefundOrder","testGroup":"bic-RefundOrder","testMethod":"validateBicRefundOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC order with existing user Financing","testcasename":"validateBicReturningUser","description":"BiC order with existing user","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-returningUser","testMethod":"validateBicReturningUser","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - estore")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - estore')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - estore')
                    }
                }
                script {
                    println("Building Testing Hub API Input Map - Account Portal")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/accountportal/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"LiftForward Financing - Account Portal Orders","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"Add Seats","testcasename":"validateBicAddSeatNativeOrder","description":"Add Seats from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-addseat-native","testMethod":"validateBicAddSeatNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Reduce Seats","testcasename":"validateBicReduceSeats","description":"Reduce Seats from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-reduceseats-native","testMethod":"validateBicReduceSeats","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Change Payment","testcasename":"validateBICChangePaymentProfile","description":"Change Payment from Portal","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-changePayment","testMethod":"validateBICChangePaymentProfile","parameters":{"application":"ece"},"testdata":{"usertype":"existing","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"Switch Term","testcasename":"validateBicNativeOrderSwitchTerm","description":"Switch Term for BiC Order","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder-switch-term","testMethod":"validateBicNativeOrderSwitchTerm","parameters":{"application":"ece","payment":"VISA","store":"STORE-NAMER"},"testdata":{"usertype":"new","password":"","payment":"FINANCING","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki": ""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - accountportal")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - accountportal')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - accountportal')
                    }
                }
            }
        }

        stage('Apollo UAT') {
            when {
                branch 'master'
                expression {
                    params.APOLLO == true
                }
            }
            steps {
                echo 'Initiating Apollo UAT'
                script {
                    println("Building Testing Hub API Input Map - estore")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/estore/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"Apollo UAT - GUAC Orders","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"BiC Native Order USA(en_US)","testcasename":"validateBicNativeOrder","description":"BiC Native Order US(en_US)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order UK(en_GB)","testcasename":"validateBicNativeOrder","description":"BiC Native Order UK(en_GB)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-UK","sku":"default:1","email":"","locale":"en_GB"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Germany(de_DE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order DE(de_DE","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Australia(en_AU)","testcasename":"validateBicNativeOrder","description":"BiC Native Order AUS(en_AU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_AU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Canada(en_CA)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CA(en_CA)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CA","sku":"default:1","email":"","locale":"en_CA"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Canada(fr_CA)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CA(fr_CA)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CA","sku":"default:1","email":"","locale":"fr_CA"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Netherlands(nl_NL)","testcasename":"validateBicNativeOrder","description":"BiC Native Order NL(nl_NL)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"nl_NL"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Poland(pl_PL)","testcasename":"validateBicNativeOrder","description":"BiC Native Order PL(pl_PL)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-PL","sku":"default:1","email":"","locale":"pl_PL"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Italy(it_IT)","testcasename":"validateBicNativeOrder","description":"BiC Native Order IT(it_IT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-IT","sku":"default:1","email":"","locale":"it_IT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Malta(en_MT)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Malta(en_MT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_MT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Norway(no_NO)","testcasename":"validateBicNativeOrder","description":"BiC Native Order NO(no_NO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-NO","sku":"default:1","email":"","locale":"no_NO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order France(fr_FR)","testcasename":"validateBicNativeOrder","description":"BiC Native Order FR(fr_FR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-FR","sku":"default:1","email":"","locale":"fr_FR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Germany(de_DE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order DE(de_DE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Spain(es_ES)","testcasename":"validateBicNativeOrder","description":"BiC Native Order SE(es_ES)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-ES","sku":"default:1","email":"","locale":"es_ES"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Finland(fi_FI)","testcasename":"validateBicNativeOrder","description":"BiC Native Order FI(fi_FI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"fi_FI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Hungary(hu_HU)","testcasename":"validateBicNativeOrder","description":"BiC Native Order HU(hu_HU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"hu_HU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Portugal(pt_PT)","testcasename":"validateBicNativeOrder","description":"BiC Native Order PT(pt_PT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"pt_PT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Austria(en_AT)","testcasename":"validateBicNativeOrder","description":"BiC Native Order AT(en_AT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_AT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Denmark(da_DK)","testcasename":"validateBicNativeOrder","description":"BiC Native Order DK(da_DK)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DK","sku":"default:1","email":"","locale":"da_DK"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Czech Republic(cs_CZ)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CZ(cs_CZ)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CZ","sku":"default:1","email":"","locale":"cs_CZ"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Switzerland(de_CH)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CH(de_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"de_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Switzerland(fr_CH)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CH(fr_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"fr_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Switzerland(it_CH)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CH(it_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"it_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Belgium(nl_BE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order BE(nl_BE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"nl_BE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Bulgaria(en_BG)","testcasename":"validateBicNativeOrder","description":"BiC Native Order BG(en_BG)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_BG"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Cyprus(en_CY)","testcasename":"validateBicNativeOrder","description":"BiC Native Order CY(en_CY)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_CY"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Croatia(en_HR)","testcasename":"validateBicNativeOrder","description":"BiC Native Order HR(en_HR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_HR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Liechtenstein(en_LI)","testcasename":"validateBicNativeOrder","description":"BiC Native Order LI(en_LI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Latvia(en_LV)","testcasename":"validateBicNativeOrder","description":"BiC Native Order LV(en_LV)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LV"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Iceland(en_IS)","testcasename":"validateBicNativeOrder","description":"BiC Native Order IS(en_IS)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_IS"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Greece(en_GR)","testcasename":"validateBicNativeOrder","description":"BiC Native Order GR(en_GR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_GR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Estonia(en_EE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order EE(en_EE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_EE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Sweden(en_SE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order SE(en_SE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Slovenia(en_SI)","testcasename":"validateBicNativeOrder","description":"BiC Native Order SI(en_SI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Slovakia(en_SK)","testcasename":"validateBicNativeOrder","description":"BiC Native Order SK(en_SK)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SK"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Ireland(en_IE)","testcasename":"validateBicNativeOrder","description":"BiC Native Order IE(en_IE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_IE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Romania(en_RO)","testcasename":"validateBicNativeOrder","description":"BiC Native Order RO(en_RO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_RO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Lithuania(en_LT)","testcasename":"validateBicNativeOrder","description":"BiC Native Order LT(en_LT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Luxembourg(en_LU)","testcasename":"validateBicNativeOrder","description":"BiC Native Order LT(en_LT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Papua New Guinea(en_PG)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Papua New Guinea(en_PG)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PG"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Cocos Island(en_CC)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Cocos Island(en_CC)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_CC"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Christmas Island(en_CX)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Christmas Island(en_CX)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_CX"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Fiji(en_FJ)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Fiji(en_FJ)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_FJ"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Marshall Island(en_MH)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Marshall Island(en_MH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_MH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Nauru(en_NR)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Nauru(en_NR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Niue(en_NU)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Niue(en_NU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Norfolk Island(en_NF)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Norfolk Island(en_NF)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NF"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Palau(en_PW)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Palau(en_PW)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PW"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Pitcarin Island(en_PN)","testcasename":"validateBicNativeOrder","description":"BiC Native Order  Pitcarin Island(en_PN)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PN"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Samoa(en_WS)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Samoa(en_WS)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_WS"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Solomon Islands(en_SB)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Solomon Islands(en_SB)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_SB"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Tonga(en_TO)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Tonga(en_TO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_TO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Tavulu(en_TV)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Tavulu(en_TV)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_TV"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Native Order Vanuatu(en_VU)","testcasename":"validateBicNativeOrder","description":"BiC Native Order Vanuatu(en_VU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"bic-nativeorder","testMethod":"validateBicNativeOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_VU"},"notsupportedenv":[],"wiki":""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - estore")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - estore')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - estore')
                    }
                }
                script {
                    println("Building Testing Hub API Input Map - Order Renewal")
                    def testingHubInputMap = [:]
                    testingHubInputMap.authClientID = 'fSPZcP0OBXjFCtUW7nnAJFYJlXcWvUGe'
                    testingHubInputMap.authCredentialsID = 'testing-hub-creds-id'
                    testingHubInputMap.testingHubApiEndpoint = 'https://api.testinghub.autodesk.com/hosting/v1/project/estore/testcase'
                    testingHubInputMap.testingHubApiPayload = '{"env":"STG","executionname":"Apollo UAT - GUAC Orders","notificationemail":["ece.dcle.platform.automation@autodesk.com"],"testcases":[' +
                            '{"displayname":"BiC Renew Order USA(en_US)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order US(en_US)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"VISA","store":"STORE-NAMER","sku":"default:1","email":""},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order UK(en_GB)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order UK(en_GB)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-UK","sku":"default:1","email":"","locale":"en_GB"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Germany(de_DE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order DE(de_DE","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Australia(en_AU)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order AUS(en_AU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_AU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Canada(en_CA)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CA(en_CA)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CA","sku":"default:1","email":"","locale":"en_CA"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Canada(fr_CA)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CA(fr_CA)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CA","sku":"default:1","email":"","locale":"fr_CA"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Netherlands(nl_NL)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order NL(nl_NL)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"nl_NL"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Poland(pl_PL)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order PL(pl_PL)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-PL","sku":"default:1","email":"","locale":"pl_PL"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Italy(it_IT)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order IT(it_IT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-IT","sku":"default:1","email":"","locale":"it_IT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Malta(en_MT)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Malta(en_MT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_MT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Norway(no_NO)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order NO(no_NO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-NO","sku":"default:1","email":"","locale":"no_NO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order France(fr_FR)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order FR(fr_FR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-FR","sku":"default:1","email":"","locale":"fr_FR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Germany(de_DE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order DE(de_DE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DE","sku":"default:1","email":"","locale":"de_DE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Spain(es_ES)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order SE(es_ES)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-ES","sku":"default:1","email":"","locale":"es_ES"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Finland(fi_FI)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order FI(fi_FI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"fi_FI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Hungary(hu_HU)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order HU(hu_HU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"hu_HU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Portugal(pt_PT)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order PT(pt_PT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"pt_PT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Austria(en_AT)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order AT(en_AT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_AT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Denmark(da_DK)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order DK(da_DK)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-DK","sku":"default:1","email":"","locale":"da_DK"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Czech Republic(cs_CZ)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CZ(cs_CZ)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CZ","sku":"default:1","email":"","locale":"cs_CZ"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Switzerland(de_CH)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CH(de_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"de_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Switzerland(fr_CH)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CH(fr_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"fr_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Switzerland(it_CH)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CH(it_CH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-CH","sku":"default:1","email":"","locale":"it_CH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Belgium(nl_BE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order BE(nl_BE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"nl_BE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Bulgaria(en_BG)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order BG(en_BG)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_BG"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Cyprus(en_CY)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order CY(en_CY)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_CY"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Croatia(en_HR)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order HR(en_HR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_HR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Liechtenstein(en_LI)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order LI(en_LI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Latvia(en_LV)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order LV(en_LV)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LV"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Iceland(en_IS)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order IS(en_IS)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_IS"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Greece(en_GR)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order GR(en_GR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_GR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Estonia(en_EE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order EE(en_EE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_EE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Sweden(en_SE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order SE(en_SE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Slovenia(en_SI)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order SI(en_SI)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SI"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Slovakia(en_SK)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order SK(en_SK)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_SK"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Ireland(en_IE)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order IE(en_IE)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_IE"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Romania(en_RO)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order RO(en_RO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_RO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Lithuania(en_LT)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order LT(en_LT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LT"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Luxembourg(en_LU)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order LT(en_LT)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-EU","sku":"default:1","email":"","locale":"en_LU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Papua New Guinea(en_PG)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Papua New Guinea(en_PG)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PG"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Cocos Island(en_CC)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Cocos Island(en_CC)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_CC"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Christmas Island(en_CX)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Christmas Island(en_CX)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_CX"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Fiji(en_FJ)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Fiji(en_FJ)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_FJ"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Marshall Island(en_MH)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Marshall Island(en_MH)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_MH"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Nauru(en_NR)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Nauru(en_NR)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NR"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Niue(en_NU)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Niue(en_NU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NU"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Norfolk Island(en_NF)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Norfolk Island(en_NF)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_NF"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Palau(en_PW)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Palau(en_PW)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PW"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Pitcarin Island(en_PN)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order  Pitcarin Island(en_PN)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_PN"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Samoa(en_WS)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Samoa(en_WS)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_WS"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Solomon Islands(en_SB)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Solomon Islands(en_SB)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_SB"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Tonga(en_TO)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Tonga(en_TO)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_TO"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Tavulu(en_TV)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Tavulu(en_TV)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_TV"},"notsupportedenv":[],"wiki":""},' +
                            '{"displayname":"BiC Renew Order Vanuatu(en_VU)","testcasename":"validateRenewBicOrder","description":"BiC Renew Order Vanuatu(en_VU)","os":"windows","testClass":"com.autodesk.ece.bic.testsuites.BICOrderCreation","testGroup":"renew-bic-order","testMethod":"validateRenewBicOrder","parameters":{"application":"ece"},"testdata":{"usertype":"new","password":"","payment":"CREDITCARD","store":"STORE-AUS","sku":"default:1","email":"","locale":"en_VU"},"notsupportedenv":[],"wiki":""}' +
                            '],"workstreamname":"dclecjt"}'
                    println("Starting Testing Hub API Call - Order Renewal")
                    if (serviceBuildHelper.ambassadorService.callTestingHubApi(testingHubInputMap)) {
                        println('Testing Hub API called successfully - Order Renewal')
                    } else {
                        currentBuild.result = 'FAILURE'
                        println('Testing Hub API call failed - Order Renewal')
                    }
                }
            }
        }
    }
}
