package com.autodesk.ece.constants;

import com.autodesk.testinghub.core.constants.BICConstants;

public class BICECEConstants extends BICConstants {

  public static final String EMAIL = "email";
  public static final String PASSWORD = "password";
  public static final String DOWNLOAD_STATUS = "downloadStatus";
  public static final String CLDCR_PLC = "CLDCR";
  public static final String SUBSCRIPTION_ID = "getPOReponse_subscriptionId";
  public static final String SUBSCRIPTION_PERIOD_START_DATE = "getPOReponse_subscriptionPeriodStartDate";
  public static final String SUBSCRIPTION_PERIOD_END_DATE = "getPOReponse_subscriptionPeriodEndDate";
  public static final String NEXT_BILLING_DATE = "response_nextBillingDate";
  public static final String PAYMENT_PROFILE_ID = "getPOReponse_storedPaymentProfileId";
  public static final String TESTINGHUB_UPDATE_FAILURE_MESSAGE = "Failed to update results to Testing hub.";
  public static final String DATE_FORMAT = "MM/dd/yyyy HH:mm:ss z";
  public static final String PRODUCT_ID = "productID";
  public static final String ADD_SEAT_QTY = "addSeatQty";
  public static final String E2E_EXECUTION_TIME = "e2e_ExecutionTime";
  public static final String ORDER_CREATION = "CreateOrder";
  public static final String SUB1_ID = "sub1ID";
  public static final String SUB2_ID = "sub2ID";
  public static final String SUB1_NEXT_BILLING_DATE = "sub1NextBillingDate";
  public static final String SUB2_NEXT_BILLING_DATE = "sub2NextBillingDate";
  public static final String SUBSCRIPTION_END_DATE = "subscriptionEndDate";
  public static final String RESPONSE_END_DATE = "response_endDate";
  public static final String STATUS = "status";
  public static final String RESPONSE_STATUS = "response_status";
  public static final String RESPONSE_AUTORENEW_ENABLED = "response_autoRenewEnabled";
  public static final String ORDER_STATE = "getPOReponse_orderState";
  public static final String FULFILLMENT_STATUS = "getPOReponse_fulfillmentStatus";
  public static final String FULFILLMENT_DATE = "getPOReponse_fulfillmentDate";
  public static final String COMPANY_NAME_DR = "companyNameDR";
  public static final String ADDRESS_DR = "addressDR";
  public static final String POSTAL_CODE_DR = "postalCodeDR";
  public static final String PHONE_NUMBER_DR = "phoneNumberDR";
  public static final String ORGANIZATION_NAME = "Organization_Name";
  public static final String FULL_ADDRESS = "Full_Address";
  public static final String ZIPCODE = "Zipcode";
  public static final String PHONE_NUMBER = "Phone_Number";
  public static final String COUNTRY = "Country";
  public static final String STATE_PROVINCE = "State_Province";
  public static final String BIC_FN = "bic_FN";
  public static final String CITY = "City";
  public static final String BIC_AGREE = "bic_Agree";
  public static final String AUTODESK_ID = "autodeskId";
  public static final String USER_NAME_NEXT_BUTTON = "userNameNextButton";
  public static final String LOGIN_PASSWORD = "loginPassword";
  public static final String LOGIN_BUTTON = "loginButton";
  public static final String GET_STARTED_SKIP_LINK = "getStartedSkipLink";
  public static final String ADD_SEATS_MODAL_SKIP_BUTTON = "//*[@data-testid=\"addSeats-modal-skip-button\"]";
  public static final String PAYMENT = "payment";
  public static final String PAYMENT_TYPE = "paymentType";
  public static final String FIRSTNAME = "firstname";
  public static final String PAYPAL = "paypal";
  public static final String PAYMENT_PROFILE = "<PAYMENTPROFILE>";
  public static final String LAST_NAME = "lastName";
  public static final String CREDIT_CARD = "credit-card";
  public static final String LASTNAME = "lastname";
  public static final String FIRST_NAME = "firstName";
  public static final String CREDIT_CARD_NUMBER_FRAME = "creditCardNumberFrame";
  public static final String PAYPAL_ACCEPT_COOKIES_BTN = "paypalAcceptCookiesBtn";
  public static final String SUBMIT_ORDER_BUTTON = "SubmitOrderButton";
  public static final String CHECKED_ACH_AUTHORIZATION_AGREEMENT_IS_VISIBLE = "Checked ACH Authorization Agreement is visible - ";
  public static final String ACH_CHECKBOX_HEADER = "achCheckBoxHeader";
  public static final String CHECKED_BOX_STATUS_FOR_ACH_CHECKBOX = "Checked box status for achCheckBox - ";
  public static final String ACH_CHECKBOX = "achCheckBox";
  public static final String ID_MANDATE_AGREEMENT = "//*[@id=\"mandate-agreement\"]";
  public static final String DOCUMENT_GETELEMENTBYID_MANDATE_AGREEMENT_CLICK = "document.getElementById('mandate-agreement').click()";
  public static final String JP_ORDER_NUMBER = "//h5[.='注文番号：']/..//p";
  public static final String GUAC_RESOURCE_URL = "guacResourceURL";
  public static final String USER_TYPE = "userType";
  public static final String LANGUAGE_STORE = "languageStore";
  public static final String FIRST_NAME1 = "firstName :: ";
  public static final String LAST_NAME1 = "lastName :: ";
  public static final String ENTER_PAYMENT_DETAILS = "Enter Payment details";
  public static final String ENTER_BILLING_DETAILS = "Enter billing details";
  public static final String AFTER_ENTERING_BILLING_DETAILS = "After entering billing details";
  public static final String GUAC_CART_EDIT_QUANTITY = "guacCartEditQuantity";
  public static final String ORDER_NUMBER = "OrderNumber  :: ";
  public static final String DOWNLOAD_FREE_TRIAL_LOGIN_FRAME = "downloadFreeTrialLoginFrame";
  public static final String MOE_LOGIN_USERNAME_FIELD = "moeLoginUsernameField";
  public static final String CREDIT_CARD_FRAME_DR = "creditCardFrameDR";
  public static final String PRODUCT_PE_ID = "product_pe_id";
  public static final String EDU_ROLE = "eduRole";
  public static final String EDU_SUBMIT = "eduSubmit";
  public static final String MOE_LOGIN_PASSWORD_FIELD = "moeLoginPasswordField";
}
